### ISSUE TITLE
Collection categories titles hover color ?

### ISSUE THREAD

**Issue by anh9000** [AikoMidori/steam-library#6]
[![Image from Gyazo](https://i.gyazo.com/fbba8e826b908ecdf362cdc9faa48d88.gif)](https://gyazo.com/fbba8e826b908ecdf362cdc9faa48d88) 

I can't seem to see the option or be able to change that color. It looks like a default color or something but I don't recall having that before the new update I think. 

![image](https://user-images.githubusercontent.com/8799430/68534672-162d2a80-0305-11ea-9d23-51fe3042b301.png)

**Comment by AikoMidori** [comment]
I’ll have a look tomorrow

**Comment by AikoMidori** [comment]
Thanks for addressing the issue, i'll have a look into the files.

**Comment by AikoMidori** [comment]
Edit: it seems like you're using an outdated config file, updating it will resolve your problem.
