### ISSUE TITLE
Design Inconcistencies 

### ISSUE THREAD

**Issue by Jinxyface** [AikoMidori/steam-library#8]
So when using the most recent config.css file, the "Play" button for a game is black and blends in with the background. When hovering over it, it turns green. This is inconsistent as games that aren't installed have a purple button whether you're hovering or not.

![1](https://user-images.githubusercontent.com/19889486/71458693-9569a700-2769-11ea-8f7d-9497bbb9d70c.PNG)

![2](https://user-images.githubusercontent.com/19889486/71458696-98fd2e00-2769-11ea-89b4-f546632b633d.PNG)

I've checked in the config.css and I found the lines:

    --ButtonPlay: var(--libraryhome); /* Play button color shade 1 */
    --ButtonPlay2: var(--libraryhome); /* Play button color shade 2 */

And editing these seems to do nothing.

I've also noticed that when you input anything in the search bar, the "X" icon to clear the search has a very nasty red background to it.

![3](https://user-images.githubusercontent.com/19889486/71458736-c6e27280-2769-11ea-862f-b690d6889942.PNG)

Is there any way to fix these?

**Comment by AikoMidori** [comment]
Yes, the red X background will be removed later,
As for the play button, that’s a little mistake i made in the config file and will be fixed asap.

**Comment by Jinxyface** [comment]
Awesome. Glad to hear. I tried fixing it myself but I guess I can't figure out how to get it to read a different color haha.

Would it also be possible to make the "friend activity", "achievements" and the other sidebar elements on a game page slightly bigger to take up some of that empty space?

![1](https://user-images.githubusercontent.com/19889486/71482735-bcf05c00-27c9-11ea-923c-00497be6e289.PNG)

**Comment by MeridianGH** [comment]
I found out, that turning off the Game Play Header `GamePlayHeader: none;` results in the normal `Play` button being displayed in the color it should...

**Comment by Jinxyface** [comment]
~~Which file are you changing that in? I see it in <css folder> -> "Gamepage.css" and I see it in the config file~~

Nevermind, I found it. Much better. Thanks @MeridianPY

**Comment by Jinxyface** [comment]
As of the most recent config.css update, this issue has been resolved.
