### ISSUE TITLE
Changing activities background

### ISSUE THREAD

**Issue by MeridianGH** [AikoMidori/steam-library#9]
Hey, I can't figure out how to change the background of the activity cards...
![grafik](https://user-images.githubusercontent.com/50270402/71904620-c2a15680-3166-11ea-8a3e-12044b034cf2.png)
I don't like the look of the nearly completely black background...

Also, is it possible to add a light grey background to the achievement progress bar? The smaller progress bar at the top has a background to actually show the progress, while the one in the sidebar doesn't.
![grafik](https://user-images.githubusercontent.com/50270402/71904795-19a72b80-3167-11ea-87e0-28a6ecda4526.png)

**Comment by jakiisheep** [comment]
how did u solve this?
